### ISSUE TITLE
My instance just randomly dies with no explanation on startup.

### ISSUE THREAD

**Issue by Leopere** [kaangiray26/forte#116]
```
[sny5v ](https://swarmpit.nixc.us/#/tasks/sny5v9yg5pvaxuran76b0gahb?log=1) [32m..: Starting forte :..[0m
[sny5v ](https://swarmpit.nixc.us/#/tasks/sny5v9yg5pvaxuran76b0gahb?log=1) [32m..: Open the web player at https://forte.buzl.uk/ :..[0m
[sny5v ](https://swarmpit.nixc.us/#/tasks/sny5v9yg5pvaxuran76b0gahb?log=1) [32m..: Server:    http://0.0.0.0:3000/ :..[0m
[eiyho ](https://swarmpit.nixc.us/#/tasks/eiyhosdavt9blbxt6nmlqviw5?log=1) [32m..: Starting forte :..[0m
[eiyho ](https://swarmpit.nixc.us/#/tasks/eiyhosdavt9blbxt6nmlqviw5?log=1) [32m..: Open the web player at https://forte.buzl.uk/ :..[0m
[eiyho ](https://swarmpit.nixc.us/#/tasks/eiyhosdavt9blbxt6nmlqviw5?log=1) [32m..: Server:    http://0.0.0.0:3000/ :..[0m
[lto9q ](https://swarmpit.nixc.us/#/tasks/lto9q484a2qccfkj42sdslcar?log=1) [32m..: Starting forte :..[0m
[lto9q ](https://swarmpit.nixc.us/#/tasks/lto9q484a2qccfkj42sdslcar?log=1) [32m..: Open the web player at https://forte.buzl.uk/ :..[0m
[lto9q ](https://swarmpit.nixc.us/#/tasks/lto9q484a2qccfkj42sdslcar?log=1) [32m..: Server:    http://0.0.0.0:3000/ :..[0m
[l5llc ](https://swarmpit.nixc.us/#/tasks/l5llc9vi0c5p7ktos9gbqnih8?log=1) [32m..: Starting forte :..[0m
[l5llc ](https://swarmpit.nixc.us/#/tasks/l5llc9vi0c5p7ktos9gbqnih8?log=1) [32m..: Open the web player at https://forte.buzl.uk/ :..[0m
[l5llc ](https://swarmpit.nixc.us/#/tasks/l5llc9vi0c5p7ktos9gbqnih8?log=1) [32m..: Server:    http://0.0.0.0:3000/ :..[0m
```

**Comment by Leopere** [comment]
```yaml
version: '3.9'
x-environment:
 &default-environment
    # - POSTGRES_USER=forte     # Set Postgres Username
    # - POSTGRES_PASSWORD=forte # Set Postgres Password
    # - POSTGRES_DB=forte       # Set Postgres Database Name
    - port=3000               # Set Port
    - version="4.0"           # Set Version
    - hostname=forte.nixc.us      # Set Hostname
    - NODE_ENV=production     # Set Node Environment
    - custom_about=false      # For your own about page
    - POSTGRES_HOST=postgres  # Postgres Host/IP
    - POSTGRES_USER=forte     # Set Postgres Username
    - POSTGRES_PASSWORD=forte # Set Postgres Password
    - POSTGRES_PORT=5432      # Postgres Database Port
    - POSTGRES_DB=forte       # Set Postgres Database Name


networks:
  traefik:
    external: true
  default:
    external: false


services:
  app:
    image: kaangiray26/forte:4.0
    environment: *default-environment
    # ports:
    #     - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - /mnt/tank/persist/nixc.us/forte/production/data:/library
      - /mnt/tank/persist/nixc.us/forte/production/about:/about
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - default
      - traefik
    deploy:
      replicas: 1
      # mode: global
      placement:
        constraints:
      #     # - node.labels.role == db
      #     - node.hostname == macmini1
          - node.labels.mac-rack == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.forte.tls=true"
        - "traefik.http.services.forte.loadbalancer.server.port=3000"
        - "traefik.http.routers.forte.rule=Host(`forte.nixc.us`)"
        - "traefik.http.routers.forte.entrypoints=websecure"
        - "traefik.http.routers.forte.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.forte.service=forte"
        - "traefik.docker.network=traefik"
        - 'traefik.http.routers.forte.middlewares=authelia@docker'


  postgres:
    image: kaangiray26/postgres:2.0
    environment: *default-environment
    volumes:
      - /mnt/tank/persist/nixc.us/forte/production/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U forte" ]
      interval: 1s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          # - node.labels.role == db
          # - node.hostname == macmini8
          - node.labels.mac-rack == true
      labels:
        - "traefik.enable=false"
```

**Comment by Leopere** [comment]
Deploying this to Docker swarm with a dedicated internal network for postgres and a web ingress route through Traefik reverse proxy.  I'm not sure why exactly it would just randomly die on startup with no explanation.

**Comment by kaangiray26** [comment]
Hi, can you try again with the latest version? forte-4.1

**Comment by Leopere** [comment]
again its failing with 4.1 it says healthy for a brief moment then dies the same way.

**Comment by kaangiray26** [comment]
There is a log file `forte.log` in the docker container, it can provide you more information.

However, I'm not familiar with the settings you are using inside your `docker-compose.yml` file and can't assist you further if you are not using the original script, sorry. But you can take a look at the README to setup forte using the original `docker-compose.yml` file along with nginx as reverse proxy.

**Comment by Leopere** [comment]
This is basically the same functionally perhaps in your read me I could twist that you give that log path if you don't log to console I just used yml anchors instead of repeating myself and I use Træfik in a docker swarm context I also reduced the four space tabs down to two spaces just because that's what I use everywhere.

**Comment by Leopere** [comment]
I ran a `docker diff forte_app.1.zsena32zxquui9fxem3jjz1cq` on a downed app container and found the logs in `/forte/forte.log`

**Comment by Leopere** [comment]
logs seem blank even if I mount to host. 
```yaml
version: '3.9'
x-environment:
 &default-environment
    # - POSTGRES_USER=forte     # Set Postgres Username
    # - POSTGRES_PASSWORD=forte # Set Postgres Password
    # - POSTGRES_DB=forte       # Set Postgres Database Name
    - port=3000               # Set Port
    - version="4.1"           # Set Version
    - hostname=forte.nixc.us      # Set Hostname
    - NODE_ENV=production     # Set Node Environment
    - custom_about=false      # For your own about page
    - POSTGRES_HOST=postgres  # Postgres Host/IP
    - POSTGRES_USER=forte     # Set Postgres Username
    - POSTGRES_PASSWORD=forte # Set Postgres Password
    - POSTGRES_PORT=5432      # Postgres Database Port
    - POSTGRES_DB=forte       # Set Postgres Database Name


networks:
  traefik:
    external: true
  default:
    external: false


services:
  app:
    image: kaangiray26/forte:4.1
    environment: *default-environment
    # ports:
    #     - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - /mnt/tank/persist/nixc.us/forte/production/data:/library
      - /mnt/tank/persist/nixc.us/forte/production/about:/about
      - /mnt/tank/persist/nixc.us/forte/production/logs/forte.log:/forte/forte.log
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - default
      - traefik
    deploy:
      replicas: 1
      # mode: global
      placement:
        constraints:
      #     # - node.labels.role == db
      #     - node.hostname == macmini1
          - node.labels.mac-rack == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.forte.tls=true"
        - "traefik.http.services.forte.loadbalancer.server.port=3000"
        - "traefik.http.routers.forte.rule=Host(`forte.nixc.us`)"
        - "traefik.http.routers.forte.entrypoints=websecure"
        - "traefik.http.routers.forte.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.forte.service=forte"
        - "traefik.docker.network=traefik"
        - 'traefik.http.routers.forte.middlewares=authelia@docker'


  postgres:
    image: kaangiray26/postgres:2.0
    environment: *default-environment
    volumes:
      - /mnt/tank/persist/nixc.us/forte/production/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U forte" ]
      interval: 1s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          # - node.labels.role == db
          # - node.hostname == macmini8
          - node.labels.mac-rack == true
      labels:
        - "traefik.enable=false"
```
I really shouldn't be running into the app just randomly dying with no console feedback I've noticed you were considering adding more verbose logging into your compose example so I can wait for that upgrade.
