### ISSUE TITLE
Reverse proxy support 

### ISSUE THREAD

**Issue by mrg358** [kaangiray26/forte#83]
Pls add support to run forte behind existing reverse proxy. Basically what I need is forte running in local mode that would also work as public server behind my nginx reverse proxy.

**Comment by kaangiray26** [comment]
What is your setup like?

**Comment by mrg358** [comment]
I setup forte on my VPS behind Nginx Proxy Manager https://forte.d.numeo.top/.
Currently it's running in `local` mode, b/c `public` mode didn't worked out for me. Logs reported failing acme challenge. I think it is not possible to pass acme challenge to a container behind NPM, all certificates have to be managed by NPM.

**Comment by mrg358** [comment]
I've just tested out the latest version, docker compose with image `kaangiray26/forte:2.3`
I am happy to report that forte works now and this issue is resolved for me.
I will keep testing, and report back if necessary.
Here is my actual working docker compose file. 

```
version: '3'
services:
    app:
        image: kaangiray26/forte:2.3
        ports:
            - "10.0.0.11:8009:80"
            - "10.0.0.11:8143:443"
            - "10.0.0.11:3007:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            mode: local #local or public
            forte_email: <redacted>
            forte_server: forte.my-domain.com
            POSTGRES_HOST: postgres  # Postgres Host/IP
            POSTGRES_PORT: 5432      # Postgres Database Port
            POSTGRES_DB: forte       # Set Postgres Database Name
            POSTGRES_USER: forte     # Set Postgres Username
            POSTGRES_PASSWORD: forte # Set Postgres Password
        volumes:
            - library:/library
    postgres:
        image: kaangiray26/postgres:2.0
        restart: always
        environment:
            POSTGRES_DB: forte
            POSTGRES_USER: forte
            POSTGRES_PASSWORD: forte
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U forte" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    library:
    db-data:
```

**Comment by kaangiray26** [comment]
forte-2.4 adds some configuration to address this issue. You can now set the `mode` variable to `public` to run the server on `0.0.0.0:3000`, from which you can connect your own nginx reverse proxy. Also, all logs are now asynchronous and the node is specifically configured for production.

**Comment by mrg358** [comment]
hmm, version 2.4 for some reason doesn't work for me. 

- in public mode the app container doesn't start correctly

```
..: Starting forte :..

..: Open the web player at https://forte.buzl.uk/ :..

/node_modules/@root/greenlock/errors.js:7

        var err = new Error(msg);

                  ^

Error: please supply `maintainerEmail` as a contact for security and critical bug notices

    at E.<computed> [as NO_MAINTAINER] (/node_modules/@root/greenlock/errors.js:7:19)

    at greenlock._create (/node_modules/@root/greenlock/greenlock.js:37:25)

    at G.create (/node_modules/@root/greenlock/greenlock.js:482:15)

    at setup (file:///server.js:9:25)

    at init (file:///server.js:77:19)

    at file:///server.js:96:1

    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {

  code: 'NO_MAINTAINER',

  context: 'create'

}

Node.js v19.7.0
```

- in local mode it seems everything ok, but i can't connect, service likely not exposed.

```
..: Starting forte :..

..: Open the web player at https://forte.buzl.uk/ :..

Server:    http://localhost:3000/
```

- my actual compose file

```
version: '3'
services:
    app:
        image: kaangiray26/forte:2.4
        restart: on-failure
        ports:
            - "10.0.0.11:3007:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            mode: local              # Set to local, public or greenlock
            port: 3000               # Set Port
            NODE_ENV: production     # Set Node Environment
            POSTGRES_HOST: postgres  # Postgres Host/IP
            POSTGRES_PORT: 5432      # Postgres Database Port
            POSTGRES_DB: forte       # Set Postgres Database Name
            POSTGRES_USER: forte     # Set Postgres Username
            POSTGRES_PASSWORD: forte # Set Postgres Password
        volumes:
            - library:/library
```

older forte version 2.3 still works for me in local mode

```
Warning: connect.session() MemoryStore is not

designed for a production environment, as it will leak

memory, and will not scale past a single process.

Server:    http://localhost:3000/

=> Checking tables...

=> OK
```
