### ISSUE TITLE
Can't get forte running (pt. 2)

### ISSUE THREAD

**Issue by JaxzKyd** [kaangiray26/forte#88]
So I noticed that 1.7 just released, meaning I could finally use my entire music library with Forte, which I was excited to test out! Unfortunately, trying to start forte leads to the app container closing with these logs.
- [_forte-app-1_logs.txt](https://github.com/kaangiray26/forte/files/10853889/_forte-app-1_logs.txt)

**Comment by kaangiray26** [comment]
Hi, forte uses [music-metadata](https://github.com/Borewit/music-metadata) library for checking out if the file is an audio file. Do you have any files that are not supported by music-metadata?

You can check the supported files [here](https://github.com/Borewit/music-metadata#support-for-audio-file-types)

I'll try to make a workaround for unsupported files :+1:

**Comment by JaxzKyd** [comment]
> Hi, forte uses music-metadata library for checking out if the file is an audio file. Do you have any files that are not supported by music-metadata?
I don't believe I do. My library mainly comprises FLACs with the occasional MP3s and OGG files. All of which seems to be listed. I'll try a smaller portion of my library that I know only consists of FLACs and I'll get back to you.

**Comment by kaangiray26** [comment]
I've pushed some changes to revert to manual tagging if parseFile function fails. Can you check if it solves the issue for you?

You can use the following `docker-compose.yml` file to build from the master branch quickly:

```
version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.node
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            mode: local
            forte_email: <email>
            forte_server: <server>
            POSTGRES_HOST: postgres  # Postgres Host/IP
            POSTGRES_PORT: 5432      # Postgres Database Port
            POSTGRES_DB: forte       # Set Postgres Database Name
            POSTGRES_USER: forte     # Set Postgres Username
            POSTGRES_PASSWORD: forte # Set Postgres Password
        volumes:
            - <library>:/library
    postgres:
        build:
            context: .
            dockerfile: Dockerfile.postgres
        restart: always
        environment:
            POSTGRES_DB: forte       # Set Postgres Database Name
            POSTGRES_USER: forte     # Set Postgres Username
            POSTGRES_PASSWORD: forte # Set Postgres Password
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U forte" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db-data:
```
